### ISSUE TITLE
-webkit-line-clamp not working in Angular 8

### ISSUE THREAD

**Issue by mharoot** [mharoot/MyPlanner#3]
# Angular Version
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.4
Node: 12.4.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.4
@angular-devkit/core         8.0.4
@angular-devkit/schematics   8.0.4
@schematics/angular          8.0.4
@schematics/update           0.800.4
rxjs                         6.4.0
```

# style.css
```css
  .col.one-hour {
  /*   position: relative;
    top:-22px; */ 
    margin:1px;
    padding:1px;
    width:100%;
    height:120px;
    background-color:lightgreen;
    border: 1px;
    border-style: solid;
    overflow: hidden; 
    display: -webkit-box;
      -webkit-line-clamp: 5;
      -webkit-box-orient: vertical;

  }
  
  .col.fourty-five-min {
  /*   position: relative;
    top:-22px;  */
    margin:1px;
    padding:1px;
    width:100%;
    height:95px;
    background-color:lightgreen;
    border: 1px;
    border-style: solid;
    overflow: hidden; 
    display: -webkit-box;
      -webkit-line-clamp: 4;
      -webkit-box-orient: vertical;
  }
```
